trainer: forces
hide_eval_progressbar: True

dataset:
  - src: YOUR_DATA_PATH/s2ef/2M/train/
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: YOUR_DATA_PATH/s2ef/all/val_id/

logger: wandb

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

model:
  name: gmnoc
  cutoff: 8.0
  regress_forces: True
  force_head: 'combine'
  return_mask: false
  num_kernel: 128
  attention_heads: 48
  enable_edge_types: True
  use_pbc: True
  otf_graph: True
  hidden_dim: 512
  vec_dim: 96
  n_head: 16
  n_layers: 10
  backbone: 'GMN'
  disable_field: false
  num_gaussians: 128
  basis_width_scalar: 2.0
  max_num_elements: 90
  max_num_neighbors: 40
  num_r_samples: 1
  radius_k: 1
  norm_type: 'post'
  residual: true
  combine_type: 'mlp'
  learnable_frame: false
  sampling_scope: 'local'
  local_radius_cutoff: 0.0
  concat_r_to_z: false
  share_basis: true
  recycle_num: 1

optim:
  batch_size: 4
  eval_batch_size: 4
  num_workers: 16
  eval_every: 5000
  max_epochs: 9999
  max_steps: 200000

  optimizer: AdamW
  optimizer_params:
    amsgrad: True

  lr_initial: 0.0004

  lr_gamma: 0.5
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 100000
    - 140000
    - 180000

  warmup_steps: 100
  warmup_factor: 0.2
  force_coefficient: 100
  energy_coefficient: 2
  clip_grad_norm: 10
  ema_decay: 0.999
  loss_energy: mae
  loss_force: l2mae
